######################################################################
# Automatically generated by qmake (3.0) Wed Dec 17 00:39:29 2014
######################################################################

QT += testlib
CONFIG += c++11
TEMPLATE = app
TARGET = tests
INCLUDEPATH += .

# Input
HEADERS += ../controller/blockingqueue.h \
           ../common/events/ievent.h \
           ../common/events/streetfieldaddedevent.h \
           ../common/coordinates.h
SOURCES += tst_testsclass.cpp \
           ../controller/blockingqueue.cpp \
           ../common/events/ievent.cpp \
           ../common/events/streetfieldaddedevent.cpp
